### ISSUE TITLE
Ошибка при запуске Error

### ISSUE THREAD

**Issue by n3tpil0ts** [shamhi/PocketFiBot#1]
`(venv) root@ruvds-az6mu:~/PocketFiBot# python3 main.py
Traceback (most recent call last):
  File "/root/PocketFiBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/PocketFiBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/PocketFiBot/bot/utils/launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "/root/PocketFiBot/venv/lib/python3.9/site-packages/better_proxy/__init__.py", line 1, in <module>
    from .proxy import Proxy
  File "/root/PocketFiBot/venv/lib/python3.9/site-packages/better_proxy/proxy.py", line 16, in <module>
    def _load_lines(filepath: Path | str) -> list[str]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'`

Прокси не использую, стоит false

**Comment by n3tpil0ts** [comment]
<img width="724" alt="Screenshot 2024-04-08 at 20 05 38" src="https://github.com/shamhi/PocketFiBot/assets/60810642/a8263012-6aa1-48fc-a72f-4e0f20dfe32f">

**Comment by shamhi** [comment]
версия питона маленькая, установи 3.10 или 3.11

**Comment by avtosubaru25** [comment]
> версия питона маленькая, установи 3.10 или 3.11

Александр здравствуйте спасибо огромное за ваши проекты учусь на них  )))))    у меня вопрос уже всю голову сломал подскажите как получить веб токен , они его  по другому представляют  и я немогу в джаве разобраться    вот этот проект               web_view = await self.tg_client.invoke(RequestWebView(
                peer=await self.tg_client.resolve_peer('bittonapp_bot'),
                bot=await self.tg_client.resolve_peer('bittonapp_bot'),
                platform='android',
                from_bot_menu=False,
                url='https: // office.bitton.live '
            ))
            auth_url = web_view.url
